ALTER TYPE "public"."priority" ADD VALUE 'confirmar';--> statement-breakpoint
ALTER TYPE "public"."role" ADD VALUE 'visitante';--> statement-breakpoint
CREATE TABLE "login_attempts" (
	"id" serial PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"attempted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "google_rating" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "legacy_id" text;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "recommended_services" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "survey_status" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "survey_date" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "in_person_confirmed" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "campaign" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "visit_order" integer;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "suggested_day" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "last_contact_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "last_contact_result" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "next_follow_up_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "follow_up_stage" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "preferred_channel" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "objection" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "responsible_name" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "qualification" jsonb;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "notion_url" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "imported_at" timestamp with time zone;--> statement-breakpoint
CREATE INDEX "login_attempts_identifier_idx" ON "login_attempts" USING btree ("identifier","attempted_at");--> statement-breakpoint
CREATE UNIQUE INDEX "clients_legacy_id_idx" ON "clients" USING btree ("legacy_id");--> statement-breakpoint
-- The default value on clients.stage depends on the "stage" type, so it
-- must be dropped before the type can be dropped and recreated with the
-- full 9-value set, then restored afterward (drizzle-kit's autogenerated
-- drop/recreate strategy misses this and fails with "cannot drop type
-- stage because other objects depend on it").
ALTER TABLE "public"."clients" ALTER COLUMN "stage" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "public"."clients" ALTER COLUMN "stage" SET DATA TYPE text;--> statement-breakpoint
DROP TYPE "public"."stage";--> statement-breakpoint
CREATE TYPE "public"."stage" AS ENUM('nao_contatado', 'diagnostico_feito', 'visitado', 'whatsapp_enviado', 'ligacao_feita', 'reuniao_marcada', 'proposta_enviada', 'fechado', 'sem_interesse');--> statement-breakpoint
ALTER TABLE "public"."clients" ALTER COLUMN "stage" SET DATA TYPE "public"."stage" USING "stage"::"public"."stage";--> statement-breakpoint
ALTER TABLE "public"."clients" ALTER COLUMN "stage" SET DEFAULT 'nao_contatado';